/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './font-awesome.component';
const styles_FontAwesomeComponent:any[] = ([] as any[]);
export const RenderType_FontAwesomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FontAwesomeComponent,data:{}});
export function View_FontAwesomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'i',[['aria-hidden','true']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵdid(278528,(null as any),0,i1.NgClass,[i0.IterableDiffers,
      i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],{klass:[0,'klass'],ngClass:[1,
      'ngClass']},(null as any)),(_l()(),i0.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    var _co:i2.FontAwesomeComponent = _v.component;
    const currVal_0:any = i0.ɵinlineInterpolate(1,'fa fa-',_co.name,'');
    const currVal_1:any = _co.options;
    _ck(_v,2,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_FontAwesomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'fa',([] as any[]),
      (null as any),(null as any),(null as any),View_FontAwesomeComponent_0,RenderType_FontAwesomeComponent)),
      i0.ɵdid(114688,(null as any),0,i2.FontAwesomeComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FontAwesomeComponentNgFactory:i0.ComponentFactory<i2.FontAwesomeComponent> = i0.ɵccf('fa',
    i2.FontAwesomeComponent,View_FontAwesomeComponent_Host_0,{name:'name',size:'size',
        fixed:'fixed',animation:'animation',rotate:'rotate',spin:'spin',inverse:'inverse',
        quote:'quote',border:'border',pull:'pull'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUGVyc29uYWwvbmd4LWljb25zL3NyYy9mb250LWF3ZXNvbWUvZm9udC1hd2Vzb21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9QZXJzb25hbC9uZ3gtaWNvbnMvc3JjL2ZvbnQtYXdlc29tZS9mb250LWF3ZXNvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovUGVyc29uYWwvbmd4LWljb25zL3NyYy9mb250LWF3ZXNvbWUvZm9udC1hd2Vzb21lLmNvbXBvbmVudC50cy5Gb250QXdlc29tZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovUGVyc29uYWwvbmd4LWljb25zL3NyYy9mb250LWF3ZXNvbWUvZm9udC1hd2Vzb21lLmNvbXBvbmVudC50cy5Gb250QXdlc29tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxpIGNsYXNzPVwiZmEgZmEte3tuYW1lfX1cIiBbbmdDbGFzc109XCJvcHRpb25zXCIgYXJpYS1oaWRkZW49XCJ0cnVlXCI+PC9pPlxuICAiLCI8ZmE+PC9mYT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLHFDQUFBO2tEQUFBO01BQUEsMkJBQXFFOztJQUFsRTtJQUF1QjtJQUExQixXQUFHLFVBQXVCLFNBQTFCOzs7O29CQ0RKO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7OzsifQ==
